### indexing in higher dimensions

In [1]:
import numpy as np

In [2]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2[1]

array([4, 5, 6])

In [6]:
arr2[0,2]

3

In [7]:
arr2[0][2]

3

In [8]:
arr3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [9]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
arr3d[0]

array([[1, 2],
       [3, 4]])

In [12]:
arr3d[0,0,1]

2

In [14]:
arr3d[0]=99

In [15]:
arr3d

array([[[99, 99],
        [99, 99]],

       [[ 5,  6],
        [ 7,  8]]])

In [16]:
x=arr3d[1]

In [17]:
x

array([[5, 6],
       [7, 8]])

In [19]:
x[1,1]=55

In [20]:
arr3d

array([[[99, 99],
        [99, 99]],

       [[ 5,  6],
        [ 7, 55]]])

### Slicing in higher dimensions

In [23]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d[:2][:1]

array([[1, 2, 3]])

In [27]:
arr2d[:2][1:]

array([[4, 5, 6]])

In [28]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2d[1:][:1]

array([[4, 5, 6]])

### Here we can see we are going from left to rigth and then appling slicing on the resultes sliced array

### Now we will try to slcice in both the deminsion

In [30]:
arr2d[,:2]

SyntaxError: invalid syntax (3029888767.py, line 1)

In [31]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])