# Boolean Indexing

In [1]:
import numpy as np

In [3]:
arr=np.array(['Bob','Joe','Will','Bob'])

In [4]:
x=np.random.randn(4,4)

In [5]:
arr

array(['Bob', 'Joe', 'Will', 'Bob'], dtype='<U4')

In [6]:
x

array([[-2.0286098 ,  0.6328047 , -0.10858045,  1.55245771],
       [ 0.62950129,  0.96633268, -0.6473792 , -0.53451579],
       [-1.31932151, -0.05340086,  0.31781573, -0.00441029],
       [ 0.49010322, -0.17670352, -0.10646755, -0.1933605 ]])

In [7]:
arr=='Bob'

array([ True, False, False,  True])

In [8]:
x[arr=='Bob']

array([[-2.0286098 ,  0.6328047 , -0.10858045,  1.55245771],
       [ 0.49010322, -0.17670352, -0.10646755, -0.1933605 ]])

### This is passing boolean indexes in array that is true is to select that index and false not to select

In [9]:
x[arr=="Bob",:2]

array([[-2.0286098 ,  0.6328047 ],
       [ 0.49010322, -0.17670352]])

In [10]:
arr2=[arr=="Bob"]

In [11]:
arr2[:]='abc'

In [12]:
arr

array(['Bob', 'Joe', 'Will', 'Bob'], dtype='<U4')

In [13]:
arr2

['a', 'b', 'c']

### boolean index always create a copy

In [14]:
data=np.random.randn(10)

In [15]:
data

array([ 1.21733044, -1.21134553,  1.53644893, -0.76928404,  0.80540352,
       -0.75477606, -2.96686893, -1.30621881,  1.07382281, -2.64047245])

In [16]:
data[data>0]

array([1.21733044, 1.53644893, 0.80540352, 1.07382281])

# Fancy indexing

In [17]:
arr=np.empty((8,4))

In [18]:
arr

array([[1.40321079e-311, 1.04741917e-321, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.15998412e-028, 4.31603868e-080,
        1.94919985e-153],
       [1.35717430e+131, 4.67105225e-062, 3.45374415e-086,
        5.15533735e-062],
       [1.31424663e-047, 2.48103384e-091, 3.85467474e-057,
        4.43572649e-038],
       [8.52430844e-096, 6.01347002e-154, 9.06152375e-043,
        5.40165657e-067],
       [4.66302214e-033, 1.65645494e-076, 1.05133756e-153,
        8.97630146e-067],
       [3.65482061e-086, 2.10857695e-052, 4.99874708e+217,
        4.47303447e-143],
       [1.46899974e+179, 9.08367237e+223, 1.16466228e-028,
        1.03785306e-314]])

In [19]:
for i in range(8):
    arr[i]=i

In [20]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [21]:
arr[[-3]]

array([[5., 5., 5., 5.]])

In [22]:
arr[-3]

array([5., 5., 5., 5.])

In [23]:
arr[4,3]

4.0

In [24]:
arr[[4,3]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.]])

In [26]:
arr=np.arange(32).reshape(8,4)

In [27]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [28]:
arr[[1,5,4,7]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [16, 17, 18, 19],
       [28, 29, 30, 31]])

In [29]:
arr[[1,5,4,7],[0,3,1,2]]

array([ 4, 23, 17, 30])

In [32]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Try to undestand what is this

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [35]:
arr[[1,5,7,2]][:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [36]:
temp=arr[[1,5,7,2]]

In [37]:
temp

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [38]:
temp[:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [39]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### here what I can understand is that we are defining whar must come in the digonal andwe are shifting th current element in the digonal to thr right

### trying to prove

In [40]:
arr=np.arange(1,10).reshape(3,3)

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr[:,[1,0,2]] # 213 645 789

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

### element is comming in the digonal but how the swapping in happeing I am unable to understand