In [7]:
import numpy as np

## Diiferent ways to difine nd araay

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.empty(5)

array([1.09753223e-311, 1.09755656e-311, 1.09755656e-311, 0.00000000e+000,
       0.00000000e+000])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3)

array([0, 1, 2])

In [13]:
np.ones(3)

array([1., 1., 1.])

### defining type in ndarray

In [14]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [15]:
np.arange(start=2,stop=6,dtype=float)

array([2., 3., 4., 5.])

### changing the data type

In [16]:
x=np.arange(5)

In [17]:
x

array([0, 1, 2, 3, 4])

In [18]:
x.dtype

dtype('int32')

In [19]:
x.astype(float)

array([0., 1., 2., 3., 4.])

In [20]:
x.dtype

dtype('int32')

##### changing the type using astype is coping the array ,the original dtype is same

In [21]:
y=np.array([2.5,6.7,3.2])

In [22]:
y

array([2.5, 6.7, 3.2])

In [24]:
y.dtype

dtype('float64')

In [25]:
y.astype(int)

array([2, 6, 3])

##### value is trancated in case of astyoe from float to int