# Arithmethic with NumPy Arrays

In [9]:
import numpy as np

###  Arithmethic in numpy arrays happens element wise

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
1/arr

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_14352\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

# Indexing and Slicing in numpy Array

### When Slicing an array in numpy only a View of the original aarray is created and not the array in copied like the build in list

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[2:4]

array([2, 3])

In [12]:
arr[2:3]*10

array([20])

In [13]:
arr[2:4]*10

array([20, 30])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[2:4]=10

In [16]:
arr

array([ 0,  1, 10, 10,  4,  5,  6,  7,  8,  9])

### arr*10 does not mean assiging arr a value,  original view means arr[2:4]=9 now this will get reflectedin the original array


In [17]:
x=arr[4:7]

In [18]:
arr

array([ 0,  1, 10, 10,  4,  5,  6,  7,  8,  9])

In [19]:
x=x*5

In [20]:
x

array([20, 25, 30])

In [21]:
arr

array([ 0,  1, 10, 10,  4,  5,  6,  7,  8,  9])

In [22]:
x[1]=66

In [23]:
arr

array([ 0,  1, 10, 10,  4,  5,  6,  7,  8,  9])

In [24]:
x

array([20, 66, 30])

In [25]:
x=arr[5:8]

In [26]:
x

array([5, 6, 7])

In [27]:
x[1] = 12345

In [28]:
x

array([    5, 12345,     7])

In [29]:
arr

array([    0,     1,    10,    10,     4,     5, 12345,     7,     8,
           9])

In [30]:
x[:]=10

In [31]:
x

array([10, 10, 10])

In [32]:
arr

array([ 0,  1, 10, 10,  4, 10, 10, 10,  8,  9])

In [33]:
x=x* 99

In [34]:
x

array([990, 990, 990])

In [35]:
arr

array([ 0,  1, 10, 10,  4, 10, 10, 10,  8,  9])

### we can see that we reference x=x*5 a copy og the array is created but when we slice this arr as x[:] the original arr view is reflected and the view is changed

## Creating a copy of array

In [36]:
y=arr[5:8].copy()

In [37]:
y[2]=4

In [38]:
y

array([10, 10,  4])

In [39]:
arr

array([ 0,  1, 10, 10,  4, 10, 10, 10,  8,  9])