#  Introduction To Numpy

In [1]:
import numpy as np

In [5]:
data=np.random.randn(2,3)

In [6]:
data

array([[-0.50608811, -0.41656823, -1.84532705],
       [-0.83952949,  0.28339927,  0.16852105]])

In [7]:
data*10

array([[ -5.06088107,  -4.16568229, -18.45327045],
       [ -8.39529488,   2.83399267,   1.68521049]])

In [8]:
data + 4

array([[3.49391189, 3.58343177, 2.15467295],
       [3.16047051, 4.28339927, 4.16852105]])

In [9]:
data + data

array([[-1.01217621, -0.83313646, -3.69065409],
       [-1.67905898,  0.56679853,  0.3370421 ]])

## Desc about ndarray

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
type(data)

numpy.ndarray

##  Creating ndarray from list

In [14]:
list=[1,2,3,4,5]
data2=np.array(list)
print(data2)

[1 2 3 4 5]


In [15]:
type(data2)

numpy.ndarray

In [16]:
data2

array([1, 2, 3, 4, 5])

In [17]:
print(data2)

[1 2 3 4 5]


### ndarray from list (2d)

In [20]:
list2=[[1,2,3],[4,5,6]]
data3=np.array(list2)
data3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
data3.shape

(2, 3)

In [22]:
data3.ndim

2

## unless expecitly specify np.array infer a good data type for the array