a) Given the following commands to create series sr

import numpy as np
import pandas as pd
sr = pd.Series([‘Madhuri’,’AjaySh@rma’, ‘R@ni’, ‘Radha’,np.nan,’Smita’,’3567’])
Write separate commands to compute the length of each string in the
series, replace @ with ‘a’ in all strings in the series, count the
occurrences of ‘a’ in each string, change the case of all letters, find all
strings with pattern ‘adh’ in them and find all strings that end with
letter ‘i’.


b) Create a DataFrame of 7 rows and 7 columns containing random
integers in the range of 1 to 100. Compute the correlation of each row
with the preceding row.


c) Write Numpy code to generate a random list of 100 integers (range of
55 to 150) and identify the index of the largest element and smallest
element. Change this list into a 10 x 10 matrix and replace all diagonal
elements with 1.

### a)
Given the following commands to create series sr

import numpy as np import pandas as pd
sr = pd.Series([‘Madhuri’,’AjaySh@rma’, ‘R@ni’, ‘Radha’,np.nan,’Smita’,’3567’]) 

Write separate commands to compute the length of each string in the series, replace @ with ‘a’ in all strings in the series, count the occurrences of ‘a’ in each string, change the case of all letters, find all strings with pattern ‘adh’ in them and find all strings that end with letter ‘i’.

In [2]:
import numpy as np
import pandas as pd

In [5]:
sr = pd.Series(['Madhuri','AjaySh@rma', 'R@ni', 'Radha',np.nan,'Smita','3567'])

### length of strings

In [9]:
for i in sr:
    if type(i)==str:
        print(i,"     length is ",len(i))

Madhuri      length is  7
AjaySh@rma      length is  10
R@ni      length is  4
Radha      length is  5
Smita      length is  5
3567      length is  4


### replace @ with a

In [12]:
for i in sr:
    if type(i)==str:
        i=i.replace("@",'a')
        print(i)

Madhuri
AjaySharma
Rani
Radha
Smita
3567


### count a in strings

In [15]:
for i in sr:
    if type(i)==str:
        print('a count in',i, i.count('a'))

a count in Madhuri 1
a count in AjaySh@rma 2
a count in R@ni 0
a count in Radha 2
a count in Smita 1
a count in 3567 0


### change case


In [19]:
for i in sr:
    if type(i)==str:
        x=""
        for j in i:
            if j.islower():
                x=x+j.upper()
            elif j.isupper():
                x=x+j.lower()
        print(x)

mADHURI
aJAYsHRMA
rNI
rADHA
sMITA



### find all strings with pattern ‘adh’ in them

In [20]:
for i in sr:
    if type(i)==str:
        if i.find('adh')!=-1:
            print(i)

Madhuri
Radha


### find all strings that end with letter ‘i’.

In [23]:
for i in sr:
    if type(i)==str:
        if i[-1]=='i':
            print(i)

Madhuri
R@ni


## b
b) Create a DataFrame of 7 rows and 7 columns containing random integers in the range of 1 to 100. Compute the correlation of each row with the preceding row.

In [31]:
obj=pd.DataFrame(np.random.randint(101,size=49).reshape(7,7))
obj

0   1   2   3   4   5   6
0  92  26  31  17  81  92  50
1  49  47  60  99  81  94  12
2  44  35  47  36  70  44  83
3  50  48   5  81  95  38  20
4   0  17  61  32  12  13  13
5  84  46  52   3  51  67  38
6   9  69  86  89  85  73  40

In [33]:
for i in range(1,7):
    print(obj[i].corr(obj[i-1]))

-0.10716687724211658
0.30885058147747657
0.15168012625082689
0.540794380786402
0.5864193410074704
0.08413476006283999


### c)
Write Numpy code to generate a random list of 100 integers (range of 55 to 150) and identify the index of the largest element and smallest element. Change this list into a 10 x 10 matrix and replace all diagonal elements with 1.

In [54]:
arr=np.random.randint(low=55,high=151,size=100)

In [55]:
np.where(arr==arr.min())

(array([76, 97], dtype=int64),)

In [56]:
np.where(arr==arr.max())

(array([84], dtype=int64),)

In [58]:
arr2=arr.reshape(10,10)
arr2

array([[122,  61,  91, 138,  66,  96, 148, 145,  63,  60],
       [ 97, 121,  97,  87, 148, 123, 145,  64,  81, 107],
       [ 70, 119,  93, 124, 146, 119,  92, 145,  60,  94],
       [116,  77,  97, 136, 122, 129,  67, 118, 102,  84],
       [123, 120,  77,  91,  91, 120,  75, 146,  58,  92],
       [ 97, 127, 116, 118, 145, 143, 115,  94, 133,  68],
       [ 91,  67, 127, 147, 121, 136,  75,  72,  87,  93],
       [ 78, 107,  91,  96, 128,  75,  56,  73, 148,  90],
       [119,  96, 138, 117, 150,  70,  58, 133, 136, 129],
       [104,  90, 130,  61,  58,  76,  95,  56, 141, 129]])

In [83]:
x=arr2.shape[0]-1
y=0
for i in range(arr2.shape[0]):
    arr2[i][i]=1
    arr2[x][y]=1
    x=x-1
    y=y+1
    
arr2
    

array([[  1,  61,  91, 138,  66,  96, 148, 145,  63,   1],
       [ 97,   1,  97,  87, 148, 123, 145,  64,   1, 107],
       [ 70, 119,   1, 124, 146, 119,  92,   1,  60,  94],
       [116,  77,  97,   1, 122, 129,   1, 118, 102,  84],
       [123, 120,  77,  91,   1,   1,  75, 146,  58,  92],
       [ 97, 127, 116, 118,   1,   1, 115,  94, 133,  68],
       [ 91,  67, 127,   1, 121, 136,   1,  72,  87,  93],
       [ 78, 107,   1,  96, 128,  75,  56,   1, 148,  90],
       [119,   1, 138, 117, 150,  70,  58, 133,   1, 129],
       [  1,  90, 130,  61,  58,  76,  95,  56, 141,   1]])