2. Write programs in Python using NumPy library to do the following:

a. Compute the mean, standard deviation, and variance of a two dimensional random integer array
along the second axis.

b. Get the indices of the sorted elements of a given array.
a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data
type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of
these elements in three separate arrays.

### A

In [1]:
import numpy as np

In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[ 1.3037361 ,  0.48266485, -0.07207877,  1.03800787],
       [-0.48312554, -0.47157762,  1.36407199, -1.44946369],
       [ 0.78236873, -0.28954601,  2.03113814, -0.2516024 ],
       [-1.73652454, -0.23447826, -0.44766844, -1.04294934]])

#### mean on second axis

In [4]:
np.mean(arr,axis=1)

array([ 0.68808252, -0.26002372,  0.56808962, -0.86540514])

#### std on second axis

In [5]:
np.std(arr,axis=1)

array([0.5295089 , 1.01820723, 0.94787399, 0.58372588])

#### var on second axis

In [6]:
np.var(arr, axis=1)

array([0.28037967, 1.03674595, 0.8984651 , 0.34073591])

### B

b. Get the indices of the sorted elements of a given array. a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [7]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [8]:
np.argsort(B)

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5], dtype=int64)

In [9]:
B

[56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [10]:
#[56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
# 0    1   2   3   4   5   6   7  8  9
#we want
#[8,   2,  6,  9,  3,  7,  1,  0, 4, 5]
#[8,   22 ,24, 33 ,41, 46, 48, 56,78,91]

### C

c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

In [11]:
arr2=np.random.randint(1,100,size=(3,4))

In [12]:
arr2

array([[38, 12,  1, 99],
       [36,  4, 38,  2],
       [89, 85, 22, 88]])

In [13]:
arr2.shape

(3, 4)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
type(arr2)

numpy.ndarray

In [16]:
n=int(input("Enter value of n "))
m=int(input("Enter value of m "))
while n*m !=arr2.shape[0]*arr2.shape[1]:
    print("product must be",arr2.shape[0]*arr2.shape[1])
    n=int(input("Enter value of n "))
    m=int(input("Enter value of m "))

Enter value of n 4
Enter value of m 4
product must be 12
Enter value of n 4
Enter value of m 3


In [17]:
arr2=arr2.reshape(n,m)

In [18]:
arr2

array([[38, 12,  1],
       [99, 36,  4],
       [38,  2, 89],
       [85, 22, 88]])

### D

d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.

In [19]:
arr3=np.array([-3,-9,0,1,np.nan,1,0,0,np.nan])

In [20]:
arr3

array([-3., -9.,  0.,  1., nan,  1.,  0.,  0., nan])

In [21]:
np.where(arr3==0)

(array([2, 6, 7], dtype=int64),)

In [22]:
np.where(arr3!=0)# nan is consider as no zero

(array([0, 1, 3, 4, 5, 8], dtype=int64),)

In [23]:
np.where(np.isnan(arr3))

(array([4, 8], dtype=int64),)